name: server_express
description: "SFTP Tool"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter_localizations:
    sdk: flutter
  ffi: ^2.1.4
  file_picker: ^10.3.7
  flutter:
    sdk: flutter
  get: ^4.7.2
  google_fonts: ^6.3.2
  loading_animation_widget: ^1.3.0
  msix: ^3.16.12
  package_info_plus: ^9.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  window_manager: ^0.5.1
  uuid: ^4.5.2
  lpinyin: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
